sudo: required

services:
    - docker

befor_install: 
    - docker build -t amitrathee987/docker-react -f Dockerfile.dev .

script:
    - echo "script part is done"

deploy: 
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "/elasticbeanstalk-ap-south-1-888796895005"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_ACCESS_KEY"

    
    